### ISSUE TITLE
allow for multiple feed ids in api enpoints

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#1007]
Currently the feed controller takes in single a feed id when working with a feed.

It would be useful to allow multiple feedid parameters to allow the feed model to act on multiple feeds.

This applies to get,set,insert,update,delete,clear and trim (and possibly others) feed api endpoints

This could be done using an `ids` parameter instead of the current `id` (_this would not effect any of the existing code_)
or the current `id` parameter could be used as a list like this: `21|12|44`

This is not high priority as the "bulk edit" features I've implemented recently simply call the single get/set/update endpoints multiple times (one for each effected feed)

**Comment by pb66** [comment]
I agree!

I like the idea of using "ids". Back when I added the "feed/fetch" endpoint to return multiple feed values in one hit, I was keeping it separate to the existing single feed api to avoid confusion, since then I have wondered if I should have just altered the existing feed api to use "ids" rather than "id" and adding a separate feed/fetch "ids". 

Although the legacy "id" and "fetch" api's could be left in place for backwards compatibility, new feed api's could be rolled out using the "ids" as an indicator of a later revision of api's and any other necessary api changes, previously not touched in fear of breaking existing setups, could be deployed at the same time ie the use of "ids" indicates feed api "v2" and a list of one feed id is acceptable so moving forward all users (and emoncms internals) could use the new api's.

This might be a good time to review the potential future endpoints, eg day todate, week todate, month todate etc and last 24hrs, last 7 days, last 30days etc.

I'm not suggesting adding or re-writing all the endpoints now, just saying there is no reason to have to carryover a mirror image of what we have now and some thought about future possibilities at this point might make future development easier. It just looks like a good opportunity to include some other changes too.

**Comment by emrysr** [comment]
This would be very useful for current development work in requesting graphing data *feed/data.json*.

This example API call could retrieve data from multiple feeds for a graphing template as all the properties called are identical for each feed - except for the feed id...
```
/feed/data.json?id=21|91&start=1512475200000&end=1544054400000&interval=43200&skipmissing=0&limitinterval=1
```
to do this as it is now would require multiple calls to the api:
```
/feed/data.json?id=21&start=1512475200000&end=1544054400000&interval=43200&skipmissing=0&limitinterval=1
/feed/data.json?id=91&start=1512475200000&end=1544054400000&interval=43200&skipmissing=0&limitinterval=1

```


this could then return a list of json objects (one for each feed) with a new data property to allow for the api consumer to iterate through the results
```
result = [
{ 
  feedid: 21,
  data: [[1543924800000,null],[1543968000000,null],[1544011200000,null],[1544054400000,null]
},
{
  feedid: 19,
  data: [[1543924800000,null],[1543968000000,null],[1544011200000,null],[1544054400000,null]
}
]
```

**Comment by TrystanLea** [comment]
Merged https://github.com/emoncms/emoncms/pull/1138
