### ISSUE TITLE
Copy & Paste monster bit process_setting.php

### ISSUE THREAD

**Issue by deece** [emoncms/emoncms#1054]
These lines should probably set the MQTT server, not $redis_server :)

        if (isset($_ENV["EMONCMS_MQTT_HOST"]))     $redis_server['host'] = $_ENV["EMONCMS_MQTT_HOST"];
        if (isset($_ENV["EMONCMS_MQTT_PORT"]))     $redis_server['port'] = $_ENV["EMONCMS_MQTT_PORT"];
        if (isset($_ENV["EMONCMS_MQTT_USER"]))     $redis_server['user'] = $_ENV["EMONCMS_MQTT_USER"];
        if (isset($_ENV["EMONCMS_MQTT_PASSWORD"]))     $redis_server['password'] = $_ENV["EMONCMS_MQTT_PASSWORD"];
        if (isset($_ENV["EMONCMS_MQTT_BASETOPIC"]))     $redis_server['basetopic'] = $_ENV["EMONCMS_MQTT_BASETOPIC"];

**Comment by borpin** [comment]
https://github.com/emoncms/emoncms/blob/412d266c96d86e1424c00a277834ab18c579b2a2/process_settings.php#L55-L59

That has been there since [Nov 2016](https://github.com/emoncms/emoncms/commit/da3bb933d436445047c082c3515b62c61fe99047#diff-c854598429e59fc419ee302e929e3639)!!! (sorry, can't do a PR for it).
