### ISSUE TITLE
Server info conflicting info for git version

### ISSUE THREAD

**Issue by pb66** [emoncms/emoncms#1216]
Seems the git sourced version (9.9.4) info is lagging behind the emoncms inbuilt version (9.9.7-beta)

![image](https://user-images.githubusercontent.com/5606042/53432071-b8141d80-39e9-11e9-9fe6-afc8de4509b2.png)

Is this dependent on someone always remembering to do something in addition to updating the version.txt and creating the release tag?

**Comment by pb66** [comment]
Answering my own question, yes it does. I see @TrystanLea  has just posted about adding the tag annotation on the forum https://community.openenergymonitor.org/t/announcement-of-9-9-6/10067/14?u=pb66

![image](https://user-images.githubusercontent.com/5606042/53433180-d8dd7280-39eb-11e9-8842-e0e472b8fb02.png)

**Comment by pb66** [comment]
Is there supposed to be a space after the "9.9.7-1g" ? The "ae268e04" part matches the commit number and refers to a point that can be found, or am I reading it wrong?

**Comment by borpin** [comment]
I think that, because you are on master and the tag should point to a commit on stable, I'm not sure it will ever look right on master unless a 'beta' tag is created for the commit that changes the version file to 'beta'.

The hyphen tells you the relative position of your HEAD to the last annotated tag.  The number is the number of commits, but I am not sure what the g means - possibly because it is on a different branch?

This is all. I think, because master is not used for releases.
