### ISSUE TITLE
Cassandra feed engine integration

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#1768]
Hello @mabi just wondering if you are still using the cassandra engine integration?

**Comment by mabi** [comment]
> Hello @mabi just wondering if you are still using the cassandra engine integration?

not actively, but I still have a server with cassandra installed, if you want I can make some test, tell me which branch/commit shall I check out

**Comment by TrystanLea** [comment]
Thanks @mabi I've been doing a lot of work on the other feed engines but have not looked at what would be involved in updating the cassandra integration to match. I wonder if it is worthwhile to do so? My feeling is that it's best to focus on the core engines.. What feed engines are you using?

**Comment by mabi** [comment]
@TrystanLea I am using PHPFINA feeds now.
I developed Cassandra feeds as a useful exercise and because I thought it was a good idea to have a distributed DB for HA (I personally recovered Cassandra feeds from a complete node failure). I can test if cassandra is still working or we can just stop supporting it, maybe leaving a note that if someone is interested I can resume support.

**Comment by TrystanLea** [comment]
Thanks @mabi for your reply on this, much appreciated. I will have more of a think about what's best to do.
