### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by kraujinis** [emoncms/emoncms#589]
Hi,
I install fresh cms 9.7.5 copy to host. I have problem with displaying Lithuanian letters.
In Visualizations feed name looks correctly.
![visualisations](https://cloud.githubusercontent.com/assets/10329476/19831368/dc5a35ca-9e10-11e6-8dc8-d98c7e43493f.png)
When I try to look in Full screen I'm missing one letter.
![multigraph](https://cloud.githubusercontent.com/assets/10329476/19831406/a78666b0-9e11-11e6-980f-9a1366af2c0d.png)
The same problem in Dashboard view.

**Comment by pm-cz** [comment]
Hello, possibly my pull request #629 addresses this issue

**Comment by glynhudson** [comment]
Hi @pm-cz I am trying to test your PR #629 . Could you give me an example unicode to test with? I have beeing trying to use the Lithuanian character ė as used by @kraujinis above. However unlike @kraujinis I don't seem to be able to even get Emoncms to save a feed name with this character. The ė character gets replaced with a ? when the feed name is set. See example:

![screenshot 2017-01-15 at 22 30 43](https://cloud.githubusercontent.com/assets/758844/21966386/7422bae6-db72-11e6-898a-c05cdf1ab656.png)
![screenshot 2017-01-15 at 22 31 17](https://cloud.githubusercontent.com/assets/758844/21966387/743e05da-db72-11e6-8c1b-d367483d166a.png)

Therefore am I correct that the issue is not just affecting multigraph but also the main feed list? 

I have tried #629 but it does not seem to have made a difference. 

Sorry, I am quite unfamiliar with unicode characters, we don't use them often in English, however I can see the importance of Emoncms being able to handle unicode as feed name.

**Comment by pm-cz** [comment]
Hello, 
the unicode sequence I have successfully used is "směr větru" (wind direction). 

But if you are getting question mark in the feed name instead, I wonder, do you have the MySQL database configured to use utf-8 characters? Because by default the MySQL database I installed emoncms in had a problem with character set being configured to latin1 and mangling all unicode characters. But emoncms.org works with these feed names (but replaces unicode in the multigraph labels).

**Comment by pm-cz** [comment]
The problem is probably in the [Installation guide](https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md) where creating the database has following command:

`mysql> CREATE DATABASE emoncms;`

But the correct command to use UTF-8 would be

`mysql> CREATE DATABASE emoncms  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;`

or

`mysql> CREATE DATABASE emoncms  DEFAULT CHARACTER SET utf8;`

**Comment by glynhudson** [comment]
Ah yes, good point. I've not tested on an emonPi which has emoncms correctly configured. I have successfully managed to use `měr větru` as a feed name and can confirm the bug reported by @kraujinis where the unicode characters are dropped when viewing fullscreen multigraph. 

I have tested you PR and it does not seem to fix this. 

![screenshot 2017-01-15 at 23 01 05](https://cloud.githubusercontent.com/assets/758844/21966632/348fdd50-db77-11e6-8628-d88ca6621fe9.png)

## Fullscreen view 

![screenshot 2017-01-15 at 23 05 24](https://cloud.githubusercontent.com/assets/758844/21966633/34a0dac4-db77-11e6-9c81-11068b903b7e.png)

**Comment by glynhudson** [comment]
Thanks, install guide has been updated https://github.com/emoncms/emoncms/commit/34572fc568ddd4777dc6d199b1eb9d278e4d5428

**Comment by Paul-Reed** [comment]
Is there a MYSQL command to update existing?

**Comment by pm-cz** [comment]
@glynhudson : I am baffled by this, since it works on my local patched installation, see attached pictures.

The order in which this must be done: 
1. Apply the patch
2. Made changes to the multigraph and saved it (required since the characters are dropped in the saving routine)
3. Display the multigraph

![editor](https://cloud.githubusercontent.com/assets/6490320/21966712/d2d1ec00-db78-11e6-95f1-f072b65fcaba.png)
![multigraph](https://cloud.githubusercontent.com/assets/6490320/21966713/d305efb4-db78-11e6-8c14-5cda689ee94c.png)

**Comment by glynhudson** [comment]
@Paul-Reed could you try and test this on your emonPi?

**Comment by pm-cz** [comment]
@Paul-Reed: It should be `ALTER DATABASE emoncms CHARACTER SET utf8;`. But this will not fix the already created tables, there would have to be `ALTER TABLE xyz CONVERT TO CHARACTER SET utf8;` commands for them (or dumping them, fixing the character set and restoring them).

**Comment by Paul-Reed** [comment]
@glynhudson Don't have a emonpi, but just checked the default MYSQL characterset of my emonbase and it's `latin1`.
So presumably without converting the tables, the patch won't work?

**Comment by pm-cz** [comment]
Without utf-8 you would not be able to store non-ASCII letters in the database correctly (i.e. event the feed names will be wrong)

**Comment by Paul-Reed** [comment]
Not having much luck with this..

- Changed database to utf8 default
- Changed all emoncms tables to utf8

Without applying the diff I see;

![test1](https://cloud.githubusercontent.com/assets/973580/21967082/41fdfca0-db78-11e6-8ca3-66f297267f83.PNG)

So after applying the diff, a reboot, and saving a new multigraph, I see a blank multigraph;

![blank](https://cloud.githubusercontent.com/assets/973580/21967103/8364eed8-db78-11e6-94ff-19aeb5e73a6d.PNG)

...with the browser error;

![errormess](https://cloud.githubusercontent.com/assets/973580/21967109/96dbaa24-db78-11e6-8719-e47d94134de8.PNG)

**Comment by Paul-Reed** [comment]
- Just deleted my last post -
Found an issue with javascript caching causing errors.

Results to follow...

**Comment by Paul-Reed** [comment]
OK.

- Update MYSQL database to utf8
- Alter all existing emoncms tables to utf8
- Without applying diff;

![test1](https://cloud.githubusercontent.com/assets/973580/21967269/8726e032-db7b-11e6-83b4-b9054b1af8ff.PNG)

...after applying diff and reloading multigraph (after colour change);

![result](https://cloud.githubusercontent.com/assets/973580/21967275/992e0a80-db7b-11e6-91d2-4c194c829781.PNG)

I would suggest that if we merge the PR, it won't create any problems for current users with MYSQL formatted to `latin1`, but as the installation guide has been updated https://github.com/emoncms/emoncms/commit/34572fc568ddd4777dc6d199b1eb9d278e4d5428, all future installations will benefit from full utf8 support.
Existing installations who **want to** use utf8 characterset, will additionally need to convert their existing db tables to utf8.
Do you agree @glynhudson ?

**Comment by glynhudson** [comment]
Yes, agree.
