### ISSUE TITLE
Issue with 2 byte limit in pulse counter?

### ISSUE THREAD

**Issue by joverbee** [emoncms/emoncms#815]
I've been monitoring an emonth with halleffect input sensor on my gas meter on the pulse counter input for a couple of months with great success. However, since a few days the graphs i calculate from this like kwh/d for my gas cosumption fails and shows no data points. 
On the input tab however all values are correclty displayed, with pulse counter now showing about 65000. When clicking on the values and on the derived values, the graph however does not show anything above somewhere 64000. 
There seems to be a 2 byte limit in the graph, but the weird thing is, also the graph of the derived values fails in the same way (which are much lower and well below 2 byte limits, and show correctly in the values displayed in the input panel). This means that eg kwh/d shows zero (or nothing at all) while there seems nothing wrong with the value...is this a known limitations i am hitting?

**Comment by pb66** [comment]
@joverbee - You should post on the [OEM forum](https://community.openenergymonitor.org/) in the first instance for assistance of this nature. 

You will need to provide more info, maybe some screenshots. There are no such limitations in emoncms, the only limits as such are those that come from using 32bit floats, that offer precision to 7 digits, but that isn't going to be the issue here.
