### ISSUE TITLE
Enforce unique tag:name for feeds

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/emoncms#861]
At present unique tag:names are enforced at feed creation but not subsequently when tags and names are edited in the feed list. The function set_feed_fields does not check for the unique requirement https://github.com/emoncms/emoncms/blob/master/Modules/feed/feed_model.php#L741

**Comment by pb66** [comment]
_"At present unique tag:names are enforced at feed creation"_ it seems that is not the case (on emoncms.org at least), I just tried it because in my test for the  ([Problem setting up EmonCMS Sync - PHP errors](https://community.openenergymonitor.org/t/problem-setting-up-emoncms-sync-php-errors/7526/28?u=pb66)) forum discussion, I had indeed just edited the feed name in the feeds page, but the 3rd "solar" feed shown below was created from the inputs page with the name "solar" when there were already 2 feeds of the same name with the same tag.

![image](https://user-images.githubusercontent.com/5606042/41098764-77864258-6a54-11e8-8172-5d74267a9725.png)

**Comment by TrystanLea** [comment]
exists_feed_tag function https://github.com/emoncms/emoncms/blob/master/Modules/feed/feed_model.php#L96

**Comment by emrysr** [comment]
https://github.com/emoncms/emoncms/pull/867
