### ISSUE TITLE
header 'Content-Type : text' has no sub type

### ISSUE THREAD

**Issue by mbruinenberg** [emoncms/emoncms#865]
The lack of mime sub types in the header response results in issues handling EmonCMS responses at client side.

In Input.php all header content types of type text are now set to 'text'.
This must be changed to the correct mime type 'text/plain'.

**Comment by emrysr** [comment]
Hi @mbruinenberg, thanks for posting this issue.

Are you reading or posting to the the inputs when you receive this "text" content type?
Can you let me know how you call the inputs to get this "text" mime in the headers? 
Are you using one of the methods listed in the (api help section) [http://localhost/emoncms/input/api]
eg: http://localhost/emoncms/input/get

When I try the above I get "application/json" as the "Content-Type" header value...

Let me know how I can re-produce your problem so that I can take a look.

**Comment by borpin** [comment]
@emrysr - This community post may help.
https://community.openenergymonitor.org/t/emoncms-ubuntu-16-apache-2-4-php-7-input-post-issue-with-java-client/7600

**Comment by emrysr** [comment]
great - thanks!

**Comment by emrysr** [comment]
added the mime sub type text/plain to the input/post api endpoint: 
https://github.com/emoncms/emoncms/pull/873

This should fix any client issues with unrecognized content types. Will need to run more tests before I can change the content type to "application/json" - just in case it breaks other features.

thanks @borpin and @mbruinenberg
