### ISSUE TITLE
fixed height top menu dropdown

### ISSUE THREAD

**Issue by emrysr** [emoncms/emoncms#876]
The setup dropdown menu has a fixed height. If you have too many items it it not obvious on a mobile that you can scroll down to see the rest

Removing the max-height property below would make the dropdown as large as needed.

```
/*     /Theme/basic/emon-blue.css         */
.scrollable-menu {
    height: auto;
    max-height: 250px;
    overflow-y: auto;
}
```
https://github.com/emoncms/emoncms/blob/master/Theme/basic/emon-blue.css#L107

This height restriction must be there to prevent the dropdown from getting too long.

**Comment by emrysr** [comment]
if this height restriction is required then you could increase it by 1/2 a line so that you see that the list continues below the cutoff.

**Comment by glynhudson** [comment]
Thanks @emrysr . This issue is most apparent on Android mobile devices, the scroll bar is not shown therefore it's impossible for a user to know that there are additional menu items hidden below

![screenshot_20180614-145929](https://user-images.githubusercontent.com/758844/41416861-c5eb52c8-6fe3-11e8-9d06-dd05925ea84d.png)

Same menu on desktop 

![selection_253](https://user-images.githubusercontent.com/758844/41416975-067106e4-6fe4-11e8-9c61-c9934b49f7d8.png)

**Comment by emrysr** [comment]
made the dropdown taller (333px)

https://github.com/emoncms/emoncms/pull/877
