### ISSUE TITLE
Swipe action on mobile devices

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#985]
Currently, the Setup > Inputs / Feeds etc menu is small and difficult to use on mobile devices. Burger menus are already used in some Emoncms modules therefore cannot be used for the setup menu. 

One option could be to explore a swipe action in mobile devices to move between the Inputs / Feed pages, we could start by experimenting with: http://lyfeyaj.github.io/swipe/ 

First stage would implement a proof of concept the test how well it works before implementing fully.

**Comment by emrysr** [comment]
I found when highlighting text in the new edit input that the page navigated to the feeds page!
This only happens during a "fast swipe", the same action as highlighting text in a textbox..

I should have disabled this feature for laptops and desktops (anything with a mouse pointer) so that text can still be highlighted without danger of incorrectly triggering the swipe action that navigates to another page.

@TrystanLea should I re-open this issue or create another?
