### ISSUE TITLE
Trying to read value from feed to use in textbox

### ISSUE THREAD

**Issue by CambridgeEP** [emoncms/emoncms#997]
Hi,
This may be a stupid question, but I am trying to read a value from my feeds to insert into a textbox on my dashboard. 
The available feedvalue widget makes the text blurry and very restrictive editing is possible.

I have tried:
<iframe src=https://emoncms.org/feed/value.json?id=370069 </iframe>
But with this I can only get the value in "" and cannot edit the text format.

Also looking at reading out of the JSON but have no idea how... This is my attempt:
![image](https://user-images.githubusercontent.com/42642996/44525057-03b6d900-a6e0-11e8-95ca-d2f99bbacfe5.png)

Help appreciated!

**Comment by Paul-Reed** [comment]
We prefer general questions such as this to be asked in the forum, instead of raising a git issue.
https://community.openenergymonitor.org
Also, this is the emoncms core repo and not the dashboard repo.

Could you please post in the forum, and I'm sure one of the community experts will be able to assist.

**Comment by CambridgeEP** [comment]
Sorry, new to this, my bad

**Comment by Paul-Reed** [comment]
No worries!
